### ISSUE TITLE
License correct?

### ISSUE THREAD

**Issue by oliwoli** [OverlordsIII/NPCVarietyPort#1]
I was just wondering if the license (CC0) of this repo is correct? Asking because it's ARR on CF (maybe you forgot to add a license there?)

**Comment by OverlordsIII** [comment]
Sorry about that, this repo should probably be ARR since the [original mod ](https://github.com/Mr-Crabman/NPC-Variety)and [original CF Page](https://www.curseforge.com/minecraft/mc-mods/npc-variety) are both ARR.
