### ISSUE TITLE
(Issue) NPC's that have an eyepatch doesn't show properly

### ISSUE THREAD

**Issue by beautiful-lunatic** [OverlordsIII/NPCVarietyPort#12]
I have version 1.17.0-2.1.2 of this mod and NPC'S (This includes illagers too) who spawn/have an eyepatch doesn't seem to show it properly. Like, I can still see both of their eyes, its like the eyepatch is glitched or something. Let me know if you have any questions to try to explain this issue better. I can send pictures if you'd like!

Great mod by the way, Its part of the ones I need essential in my game :)

**Comment by YumatanGames** [comment]
This error should have being fixed... Could you provide a mod list and a few screenshots please?

**Comment by OverlordsIII** [comment]
Closing this for now as it's confirmed resolved on our end
