### ISSUE TITLE
Exception ticking world

### ISSUE THREAD

**Issue by TheButterbrotMan** [OverlordsIII/NPCVarietyPort#13]
Server is crashing

https://pastebin.com/YLnfsEpi

**Comment by FoxSpellCaster** [comment]
I am experiencing the same error. Randomly happening.
https://pastebin.com/YpRDkrKW

**Comment by MarvTekko** [comment]
I experience the same error on my server:
https://pastebin.com/TB3imLg5

**Comment by ShockPuppet** [comment]
Happened to us today too same error

**Comment by MarvTekko** [comment]
I just removed the NPC mod from my modpack and it then it worked fine.

**Comment by YumatanGames** [comment]
We're working on a fix, but it seems to only be affecting servers, for some reason. Did any of you had this error on a single player world?

**Comment by YumatanGames** [comment]
We just submitted a potential fix. 
Please, update, and let us know if your issue persists. 

Thank you

**Comment by FoxSpellCaster** [comment]
Excellent, keep working on it. Would love to see it back in my modpack again.

**Comment by TheButterbrotMan** [comment]
Its not a potentional fix, still is crashing.

**Comment by TheButterbrotMan** [comment]
https://pastebin.com/h7pAqwPM

**Comment by YumatanGames** [comment]
> https://pastebin.com/h7pAqwPM

We're gonna take another look.

**Comment by OverlordsIII** [comment]
Please make sure you downloaded the new version of the mod here, which should fix it: https://www.curseforge.com/minecraft/mc-mods/npc-variety-port/files/3601279
