### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by beautiful-lunatic** [OverlordsIII/NPCVarietyPort#15]
I think it may be trying to spawn a patrol or something because it mentions a pillager with an eyepatch. 

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2022-01-30, 11:09 a.m.
Description: Exception ticking world

org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_3769::method_16575(Lnet/minecraft/class_3218;Lnet/minecraft/class_2338;Ljava/util/Random;Z)Z has incompatible changes at opcode 104 in callback npcvariety.mixins.json:spawner.PillagerSpawnerMixin->@Inject::makePillagerWearEyePatch(Lnet/minecraft/class_3218;Lnet/minecraft/class_2338;Ljava/util/Random;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/class_3732;)V from mod npcvariety.
 Expected: [Lnet/minecraft/class_3732;]
    Found: [Lnet/minecraft/class_2680;]
Available: [Lnet/minecraft/class_2680;, Lnet/minecraft/class_3732;]
	at net.minecraft.class_3769.handler$bja000$makePillagerWearEyePatch$missing(class_3769.java)
	at net.minecraft.class_3769.method_16575(class_3769.java:117)
	at net.minecraft.class_3769.method_6445(class_3769.java:89)
	at net.minecraft.class_3218.method_29202(class_3218.java:396)
	at net.minecraft.class_3215.method_14161(class_3215.java:387)
	at net.minecraft.class_3215.method_12127(class_3215.java:325)
	at net.minecraft.class_3218.method_18765(class_3218.java:308)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_3769.handler$bja000$makePillagerWearEyePatch$missing(class_3769.java)
	at net.minecraft.class_3769.method_16575(class_3769.java:117)
	at net.minecraft.class_3769.method_6445(class_3769.java:89)
	at net.minecraft.class_3218.method_29202(class_3218.java:396)
	at net.minecraft.class_3215.method_14161(class_3215.java:387)
	at net.minecraft.class_3215.method_12127(class_3215.java:325)
	at net.minecraft.class_3218.method_18765(class_3218.java:308)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Zinta1'/47, l='ServerLevel[poop]', x=-1716.07, y=68.85, z=-1003.51]]
	Chunk stats: 4232
	Level dimension: minecraft:overworld
	Level spawn location: World: (-80,72,-352), Section: (at 0,8,0 in -5,4,-22; chunk contains blocks -80,-64,-352 to -65,319,-337), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 124592 game time, 173654 day time
	Level name: poop
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 15869 (now: false), thunder time: 10308 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 755987352 bytes (720 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 1.80
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics 620
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x5917
	Graphics card #0 versionInfo: DriverVersion=30.0.100.9667
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: LPDDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: LPDDR3
	Virtual memory max (MB): 11730.11
	Virtual memory used (MB): 9628.26
	Swap memory total (MB): 3680.98
	Swap memory used (MB): 821.53
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced-xray-fabric: Advanced XRay (Fabric) 0.7.0-build.10
		allarrowsinfinityfix: All Arrows Infinity Fix 1.0.0
		anthropophagy: Anthropophagy 1.18-1
		apoli: Apoli 2.1.0
		architectury: Architectury 3.4.9
		balm-fabric: Balm 2.1.0+0
		betterleads: BetterLeads 1.0.1+1.18.1
		biomemakeover: Biome Makeover 1.18.1-ALPHA5
		blue_endless_jankson: jankson 1.2.1
		calio: Calio 1.4.2
		cardinal-components-base: Cardinal Components API (base) 4.0.1
		cardinal-components-entity: Cardinal Components API (entities) 4.0.1
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.0.42
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		dawn: Dawn API 3.2.0
		fabric: Fabric API 0.44.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cdc8
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.4.0+16d92c47c8
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a9c8
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d95c8
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d95c8
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cdc8
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c6c8
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73dc8
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d95c8
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d29571c8
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378ac8
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f17c8
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cdc8
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d95c8
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b5c8
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d95c8
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f3c8
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cdc8
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca335c8
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d95c8
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d95c8
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cdc8
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d95c8
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d95c8
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cdc8
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842ec8
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d95c8
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1acc8
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.5+3ac43d95c8
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d95c8
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d95c8
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cdc8
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d7c8
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d95c8
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cdc8
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378ac8
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d95c8
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d95c8
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d95c8
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a7c8
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d95c8
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d95c8
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f55c8
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.5+b4f4f6cdc8
		fabricloader: Fabric Loader 0.12.12
		fallingtree: FallingTree 2.15.0
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 1.0.1+1.18.1
		friendsandfoes: Friends&Foes 1.2.1
		geckolib3: Geckolib 3.0.30
		grindenchantments: Grind Enchantments 1.5.0+1.18
		guardvillagers: Guard Villagers Fabric 1.0.1
		horsestatsvanilla: Horse Stats Vanilla 4.1.10
		identity: Identity 1.16.0-1.18.1
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 5.0.0-beta.2+1.18-rc1
		libninepatch: LibNinePatch 1.1.0
		minecraft: Minecraft 1.18.1
		moborigins: Mob Origins 1.8.0
		modmenu: Mod Menu 3.0.0
		no_null_processors: No Null Processors - Fabric 2.0.1+1.18.1
		npcvariety: NPC Variety 2.2.1
		omega-config: OmegaConfig 1.2.2-1.18.1
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		origins: Origins 1.2.0
		origins-classes: Origins: Classes 1.2.3
		pehkui: Pehkui 3.0.0+1.14.4-1.18
		playerabilitylib: Pal 1.5.0
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		repurposed_structures: Repurposed Structures 3.3.0+1.18.1
		roughlyenoughitems: Roughly Enough Items 7.0.339
		spawnermod: Enhanced Mob Spawners 1.1.2
		spruceui: SpruceUI 3.3.0+1.17
		terraform-shapes-api-v1: Terraform Shapes API (v1) 2.1.0
		torohealth: ToroHealth Damage Indicators 1.18-fabric-1
		trinketofundying: Trinket of Undying 2.0.1-1.18
		trinkets: Trinkets 3.1.0
		waystones: Waystones 9.0.0
		xaeroworldmap: Xaero's World Map 1.18.6.1
	Server Running: true
	Player Count: 1 / 8; [class_3222['Zinta1'/47, l='ServerLevel[poop]', x=-1716.07, y=68.85, z=-1003.51]]
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'

**Comment by YumatanGames** [comment]
This should have been fixed already. We'll take a look into it. Thank you for posting.

**Comment by OverlordsIII** [comment]
Make sure you're on the latest version of the mod, which is found [here](https://www.curseforge.com/minecraft/mc-mods/npc-variety-port/files/3601279)
