### ISSUE TITLE
Server crash when modded structures containing villagers are generated

### ISSUE THREAD

**Issue by SleepyTonia** [OverlordsIII/NPCVarietyPort#2]
> Description: Feature placement

^ In both cases ^

> java.lang.IllegalArgumentException: bound must be positive
> at java.util.Random.nextInt(Random.java:388)
> at net.minecraft.class_1646.handler$boi000$resetSkinIndexBasedOnBiome(class_1646.java:1681)
> at net.minecraft.class_1646.method_5943(class_1646.java:788)
> at net.minecraft.class_3499.method_17917(class_3499.java:425)
> at java.util.Optional.ifPresent(Optional.java:159)
> at net.minecraft.class_3499.method_15179(class_3499.java:420)
> at net.minecraft.class_3499.method_15172(class_3499.java:360)
> at net.minecraft.class_3781.method_16626(class_3781.java:125)
> at net.minecraft.class_3790.method_27236(class_3790.java:83)
> at net.minecraft.class_3790.method_14931(class_3790.java:79)
> at net.minecraft.class_3449.method_14974(class_3449.java:76)
> at net.minecraft.class_1959.method_28401(class_1959.java:356)
> at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
> at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
> at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
> at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
> at java.util.PrimitiveIterator$OfLong.forEachRemaining(PrimitiveIterator.java:189)
> at it.unimi.dsi.fastutil.longs.LongIterator.forEachRemaining(LongIterator.java:53)
> at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
> at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
> at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
> at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
> at net.minecraft.class_1959.method_8702(class_1959.java:355)
> at net.minecraft.class_2794.method_12102(class_2794.java:220)
> at net.minecraft.class_2806.method_12151(class_2806.java:89)
> at net.minecraft.class_2806.method_12154(class_2806.java:219)
> at net.minecraft.class_3898.method_17225(class_3898.java:568)
> at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
> at net.minecraft.class_3898.method_17224(class_3898.java:562)
> at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
> at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
> at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
> at net.minecraft.class_3900.method_17634(class_3900.java:58)
> at net.minecraft.class_3846.method_16907(class_3846.java:94)
> at net.minecraft.class_3846.method_16900(class_3846.java:137)
> at net.minecraft.class_3846.run(class_3846.java:105)
> at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
> at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
> at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
> at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
> at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
>
> (…)
>
>-- Feature --
> Details:
> 	Id: repurposed_structures:village_swamp
> 	Description: com.telepathicgrunt.repurposedstructures.world.structures.GenericJigsawStructure@5c8f5e99
> Stacktrace:
> 	at net.minecraft.class_1959.method_8702(class_1959.java:355)

> (…)
>
> Thread: Server thread
> Stacktrace:
> 	at java.util.Random.nextInt(Random.java:388)
> 	at net.minecraft.class_1646.handler$boi000$resetSkinIndexBasedOnBiome(class_1646.java:1681)
> 	at net.minecraft.class_1646.method_5943(class_1646.java:788)
> 	at net.minecraft.class_3499.method_17917(class_3499.java:425)
> 	at java.util.Optional.ifPresent(Optional.java:159)
> 	at net.minecraft.class_3499.method_15179(class_3499.java:420)
> 	at net.minecraft.class_3499.method_15172(class_3499.java:360)
> 	at net.minecraft.class_3781.method_16626(class_3781.java:125)
> 	at net.minecraft.class_3790.method_27236(class_3790.java:83)
> 	at net.minecraft.class_3790.method_14931(class_3790.java:79)
> 	at net.minecraft.class_3449.method_14974(class_3449.java:76)
> 	at net.minecraft.class_1959.method_28401(class_1959.java:356)
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
> 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
> 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
> 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
> 	at java.util.PrimitiveIterator$OfLong.forEachRemaining(PrimitiveIterator.java:189)
> 	at it.unimi.dsi.fastutil.longs.LongIterator.forEachRemaining(LongIterator.java:53)
> 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
> 
> -- Feature --
> Details:
> 	Id: stoneholm:underground_village
> 	Description: net.thegrimsey.stoneholm.structures.UnderGroundVillageStructure@628f8380
> Stacktrace:
> 	at net.minecraft.class_1959.method_8702(class_1959.java:355)

Happened  to me with [Repurposed Structures](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric) and [Stoneholm](https://github.com/TheGrimsey/Stoneholm).
`repurposed_structures-1.16.5-1.10.5-fabric.jar`
`stoneholm-1.2.1.jar`
`npc-variety-1.16.4-1.2.3.jar`
`fabric-api-0.32.5+1.16.jar`
`fabric-loader-0.11.3-1.16.5`
`Minecraft 1.16.5`

**Comment by TelepathicGrunt** [comment]
Actually, vanilla does have skins for jungle and swamp villagers. I use them in my Repurposed Structures mod. The Swamp Village and Dark Oak Villages spawns swamp skinned villagers. The Jungle Village spawns jungle skinned villagers.

I have been getting reports lately of this crash but couldn't figure out which mod it was until someone helped out and found it was this mod.
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/issues/116
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/issues/114

 It strangely seems to only occur when a Villager is spawned by structures instead of with a Spawn Egg in Jungles or Swamps (that gets them the jungle/swamp skins)

**Comment by OverlordsIII** [comment]
This should be fixed in `fc3ce78`.
