### ISSUE TITLE
Eyes are rendered on top of eyepatches

### ISSUE THREAD

**Issue by Mr-Crabman** [OverlordsIII/NPCVarietyPort#6]
The eyepatches should be rendered on top of the eye layer, not below it:

![image](https://user-images.githubusercontent.com/23131128/124302111-a2ced100-db58-11eb-8bb8-0318fac1ad2c.png)
![image](https://user-images.githubusercontent.com/23131128/124302675-6bacef80-db59-11eb-8b4f-6afa4eea5387.png)

**Comment by OverlordsIII** [comment]
Thanks for reporting, will fix.
