### ISSUE TITLE
Wrong eye texture used for ravagers

### ISSUE THREAD

**Issue by Mr-Crabman** [OverlordsIII/NPCVarietyPort#7]
Their eyes look wrong:
![image](https://user-images.githubusercontent.com/23131128/124303855-d874b980-db5a-11eb-8f88-f624ef55dfb8.png)

This here is the culprit I believe:
![image](https://user-images.githubusercontent.com/23131128/124303679-9ea3b300-db5a-11eb-97d1-19d010db5a5d.png)

Ravagers have a separate set of eye textures that are narrower:
![image](https://user-images.githubusercontent.com/23131128/124304030-0fe36600-db5b-11eb-81e8-fd295bf3020a.png)

**Comment by OverlordsIII** [comment]
Will fix, thanks for reporting.
