### ISSUE TITLE
Config option to use natural/original villager eye colors for cured zombie villagers

### ISSUE THREAD

**Issue by Mr-Crabman** [OverlordsIII/NPCVarietyPort#8]
This current version of the mod changes the eyes of a villager to red permanently if they have ever been a zombie villager and cured. So zombie villagers that spawn and are cured always have red eyes, and villagers that are turned into zombies and then cured *lose* their old eye color.

This may be nice for some people, but my own preference (and I'm sure the preference of others too) is to let villagers keep their eye color forever even through zombification (as in the original mod), and for newly cured zombie villagers (who spawned as zombies) to have unique eye colors when cured rather than all being the same.

As such, it would be nice to make this a config option.

**Comment by OverlordsIII** [comment]
Should be easy enough to do, will implement now.
